refactor(x11): rename things everywhere, camel_case

diff --git a/display-manager/.local/bin/startx b/display-manager/.local/bin/startx
--- a/display-manager/.local/bin/startx
+++ b/display-manager/.local/bin/startx
@@ -179,23 +179,23 @@ while getopts ":hm" option; do case ${option} in
 esac; done
 
 detect_unused_display() {
-    d=0
+    i=0
     while true
     do
-        if [ -e "/tmp/.X${d}-lock" ] || [ -S "/tmp/.X11-unix/X${d}" ]
+        if [ -e "/tmp/.X${i}-lock" ] || [ -S "/tmp/.X11-unix/X${i}" ]
         then
-            d=$(expr "${d}" + 1)
+            i=$(expr "${i}" + 1)
         else
             break
         fi
     done
-    echo ":${d}"
-    unset d
+    echo ":${i}"
+    unset i
 }
 
-teardown() {
+tear_down() {
     enable_xauth=${1}
-    xserverauthfile=${2}
+    xserver_auth_file=${2}
     shift; shift;
     if [ -n "${enable_xauth}" ]
     then
@@ -204,9 +204,9 @@ teardown() {
             # shellcheck disable=SC2086
             xauth remove "${@}"
         fi
-        if [ -n "${xserverauthfile}" ]
+        if [ -n "${xserver_auth_file}" ]
         then
-            rm -f "${xserverauthfile}"
+            rm -f "${xserver_auth_file}"
         fi
     fi
     if command -v deallocvt > /dev/null 2>&1
@@ -216,97 +216,107 @@ teardown() {
 }
 
 parse_args() {
-    whoseargs="client"
-    clientargs=''
-    serverargs=''
+    is_client='client'
+    client_arguments=''
+    server_arguments=''
     while [ -n "${1}" ]
     do
         case "${1}" in
             --)
-                whoseargs='server'
+                is_client=
             ;;
             *)
-                if [ "${whoseargs}" = 'client' ]
+                if [ -n "${is_client}" ]
                 then
-                    clientargs="${clientargs} ${1}"
+                    client_arguments="${client_arguments} ${1}"
                 else
                     # display must be the FIRST server argument
-                    if [ -z "${serverargs}" ] && \
+                    if [ -z "${server_arguments}" ] && \
                             expr "${1}" : ':[0-9][0-9]*$' > /dev/null 2>&1
                     then
                         display="${1}"
                     else
-                        serverargs="${serverargs} ${1}"
+                        server_arguments="${server_arguments} ${1}"
                     fi
                 fi
             ;;
         esac
         shift
     done
-    printf '%s\n%s\n%s\n%s\n%s\n' "${client:- }" "${clientargs:- }" "${server:- }" "${serverargs:- }" "${display:- }"
+    printf '%s\n%s\n%s\n%s\n%s\n' "${client:- }" "${client_arguments:- }" "${server:- }" "${server_arguments:- }" "${display:- }"
 }
 
 process_args() {
     read -r client
-    read -r clientargs
+    read -r client_arguments
     read -r server
-    read -r serverargs
+    read -r server_arguments
     read -r display
-    clientargs=$(echo "${clientargs}" | sed 's/^ *//')
-    serverargs=$(echo "${serverargs}" | sed 's/^ *//')
-    defaultclientargs=default
-    defaultserver=/usr/bin/X
-    defaultserverargs=''
-    sysclientrc=/etc/X11/xinit/xinitrc
-    sysserverrc=/etc/X11/xinit/xserverrc
-    userclientrc=${XINPUTRC:-${XDG_CONFIG_HOME:-${HOME}/.config}/x11/client}
-    userserverrc=${XSERVERRC:-${XDG_CONFIG_HOME:-${HOME}/.config}/x11/server}
+    active_client=
+    active_client_arguments=$(echo "${client_arguments}" | sed 's/^ *//')
+    active_server=
+    active_server_arguments=$(echo "${active_server_arguments}" | sed 's/^ *//')
+    default_client=/usr/bin/xterm
+    default_client_arguments=default
+    default_server=/usr/bin/X
+    default_server_arguments=''
+    environment_client="${XINITRC}"
+    environment_server="${XSERVERRC}"
+    system_client=/etc/X11/xinit/xinitrc
+    system_server=/etc/X11/xinit/xserverrc
+    user_client=${XDG_CONFIG_HOME:-${HOME}/.config}/x11/client
+    user_client_legacy=${HOME}/.xinitrc
+    user_server=${XDG_CONFIG_HOME:-${HOME}/.config}/x11/server
+    user_server_legacy=${HOME}/.xserverrc
 
-    if [ -f "${userclientrc}" ]; then
-        client=${userclientrc}
-    elif [ -f "${sysclientrc}" ]; then
-        client=${sysclientrc}
-    else
-        client=
+    for file in "${environment_client}" "${user_client}" "${user_client_legacy}" "${system_client}"
+    do
+        if [ -f "${file}" ]; then
+            active_client="${file}"
+            break
+        fi
+    done
+    for file in "${environment_server}" "${user_server}" "${user_server_legacy}" "${system_server}"
+    do
+        if [ -f "${file}" ]; then
+            active_server="${file}"
+            break
+        fi
+    done
+    if [ -z "${active_client}" ]
+    then
+        active_client=${default_client}
+        active_client_arguments=${default_client_arguments}
     fi
-    if [ -f "${userserverrc}" ]
+    if [ -z "${active_server}" ]
     then
-        server=${userserverrc}
-    elif [ -f "${sysserverrc}" ]
-    then
-        server=${sysserverrc}
-    else
-        server=${defaultserver}
-    fi
-    if [ -z "${clientargs}" ]
-    then
-        clientargs=${defaultclientargs}
-    fi
-    if [ -z "${serverargs}" ]
-    then
-        serverargs=${defaultserverargs}
+        active_server=${default_server}
+        active_server_arguments=${default_server_arguments}
     fi
 
-    # When starting the defaultserver start X on the current tty to avoid
+    # When starting the default_server start X on the current tty to avoid
     # the startx session being seen as inactive:
     # "https://bugzilla.redhat.com/show_bug.cgi?id=806491"
     tty=$(tty)
-    vtarg=''
+    virtual_terminal_argument=''
     if expr "$tty" : '/dev/tty[0-9][0-9]*$' > /dev/null
     then
-        tty_num=$(echo "${tty}" | grep -oE '[0-9]+$')
-        vtarg="vt${tty_num} -keeptty"
+        tty_number=$(echo "${tty}" | grep -oE '[0-9]+$')
+        virtual_terminal_argument="vt${tty_number} -keeptty"
     fi
 
-    # if no vt is specified add vtarg (which may be empty)
-    have_vtarg="no"
-    for i in ${serverargs}; do
-        if expr "$i" : 'vt[0-9][0-9]*$' > /dev/null; then
-            have_vtarg="yes"
+    # if no vt is specified add virtual_terminal_argument (which may be empty)
+    have_virtual_terminal_argument=
+    for i in ${server_arguments}
+    do
+        if expr "${i}" : 'vt[0-9][0-9]*$' > /dev/null
+        then
+            have_virtual_terminal_argument='yes'
         fi
     done
-    if [ "${have_vtarg}" = "no" ]; then
-        serverargs="${serverargs} ${vtarg}"
+    if [ -z "${have_virtual_terminal_argument}" ]
+    then
+        server_arguments="${server_arguments} ${virtual_terminal_argument}"
     fi
 
     # if no display, use default
@@ -315,78 +325,72 @@ process_args() {
         display=$(detect_unused_display)
     fi
 
-    printf '%s\n%s\n%s\n%s\n%s\n' "${client}" "${clientargs:- }" "${server}" "${serverargs:- }" "${display:- }"
+    printf '%s\n%s\n%s\n%s\n%s\n' "${active_client}" "${active_client_arguments:- }" "${active_server}" "${server_arguments:- }" "${display:- }"
 }
 
 enable_xauth() {
     read -r client
-    read -r clientargs
+    read -r client_arguments
     read -r server
-    read -r serverargs
+    read -r server_arguments
     read -r display
-
-    if [ x"${XAUTHORITY}" = x ]; then
-        XAUTHORITY=${HOME}/.Xauthority
+    if [ -z "${XAUTHORITY}" ]
+    then
+        XAUTHORITY=${XDG_CACHE_HOME:-${HOME}/.cache}/.Xauthority
         export XAUTHORITY
     fi
 
-    removelist=
-
-    # set up default Xauth info for this machine
-
-    # check for GNU hostname
     if hostname --version > /dev/null 2>&1; then
+        # check for GNU hostname
         if hostname --version 2>&1 | grep -q GNU
         then
             hostname=$(hostname -f)
         fi
     fi
-
     if [ -z "$hostname" ]; then
         hostname=$(hostname)
     fi
 
-    authdisplay=${display:-:0}
-
-    mcookie=$(/usr/bin/mcookie)
-
-    if test x"${mcookie}" = x; then
-        echo "Couldn't create cookie"
+    magic_cookie=$(/usr/bin/mcookie)
+    if [ -z "${magic_cookie}" ]
+    then
+        echo "Couldn't create magic_cookie"
         exit 1
     fi
-    dummy=0
 
     # create a file with auth information for the server. ':0' is a dummy.
-    xserverauthfile=$(mktemp --tmpdir serverauth.XXXXXXXXXX)
+    dummy=0
+    xserver_auth_file=$(mktemp --tmpdir serverauth.XXXXXXXXXX)
     # shellcheck disable=SC2064
-    trap "rm -f '${xserverauthfile}'" HUP INT QUIT ILL TRAP BUS TERM
-    xauth -q -f "${xserverauthfile}" << EOF
-add :${dummy} . ${mcookie}
+    trap "rm -f '${xserver_auth_file}'" HUP INT QUIT ILL TRAP BUS TERM
+    xauth -q -f "${xserver_auth_file}" << EOF
+add :${dummy} . ${magic_cookie}
 EOF
-
-    serverargs=${serverargs}" -auth "${xserverauthfile}
+    server_arguments=${server_arguments}" -auth "${xserver_auth_file}
 
     # now add the same credentials to the client authority file
-    # if '${displayname}' already exists do not overwrite it as another
-    # server may need it. Add them to the '${xserverauthfile}' instead.
-    for displayname in ${authdisplay} ${hostname}${authdisplay}; do
-        authcookie=$(
-            xauth list "${displayname}" \
-            | sed -n "s/.*${displayname}[[:space:]*].*[[:space:]*]//p"
+    # if '${display_name}' already exists do not overwrite it as another
+    # server may need it. Add them to the '${xserver_auth_file}' instead.
+    auth_display=${display:-:0}
+    remove_list=
+    for display_name in ${auth_display} ${hostname}${auth_display}; do
+        auth_cookie=$(
+            xauth list "${display_name}" \
+            | sed -n "s/.*${display_name}[[:space:]*].*[[:space:]*]//p"
         ) 2>/dev/null;
-        if [ -z "${authcookie}" ] ; then
+        if [ -z "${auth_cookie}" ] ; then
             xauth -q << EOF
-add ${displayname} . ${mcookie}
+add ${display_name} . ${magic_cookie}
 EOF
-            removelist="${displayname} ${removelist}"
+            remove_list="${display_name} ${remove_list}"
         else
             dummy=$(expr "${dummy}" + 1)
-            xauth -q -f "${xserverauthfile}" << EOF
-add :${dummy} . ${authcookie}
+            xauth -q -f "${xserver_auth_file}" << EOF
+add :${dummy} . ${auth_cookie}
 EOF
         fi
     done
-    printf '%s\n%s\n%s\n%s\n%s\n' "${client}" "${clientargs:- }" "${server}" "${serverargs:- }" "${display:- }"
+    printf '%s\n%s\n%s\n%s\n%s\n%s\n' "${client}" "${client_arguments:- }" "${server}" "${server_arguments:- }" "${display:- }" "${remove_list:- }"
 }
 
 main() {
@@ -400,16 +404,17 @@ main() {
         args=$(parse_args "${@}" | process_args)
     fi
     client=$(printf '%s' "${args}" | head -n 1 | tail -n 1)
-    clientargs=$(printf '%s' "${args}" | head -n 2 | tail -n 1)
+    client_arguments=$(printf '%s' "${args}" | head -n 2 | tail -n 1)
     server=$(printf '%s' "${args}" | head -n 3 | tail -n 1)
-    serverargs=$(printf '%s' "${args}" | head -n 4 | tail -n 1)
+    server_arguments=$(printf '%s' "${args}" | head -n 4 | tail -n 1)
     display=$(printf '%s' "${args}" | head -n 5 | tail -n 1)
+    remove_list=$(printf '%s' "${args}" | head -n 6 | tail -n 1)
     # shellcheck disable=SC2086
-    echo xinit "${client}" ${clientargs} -- "${server}" ${display} ${serverargs}
+    echo xinit "${client}" ${client_arguments} -- "${server}" ${display} ${server_arguments}
     exit 1
     retval=${?}
     # shellcheck disable=SC2086
-    teardown "${enable_xauth}" "${xserverauthfile}" ${removelist}
+    tear_down "${enable_xauth}" "${xserver_auth_file}" ${remove_list}
     exit ${retval}
 }
 
