docs(man): add docstring to its-terminal

diff --git a/utils/.local/bin/its-terminal b/utils/.local/bin/its-terminal
--- a/utils/.local/bin/its-terminal
+++ b/utils/.local/bin/its-terminal
@@ -1,5 +1,58 @@
 #!/usr/bin/env sh
-# Select and exec a terminal emulator.
+#h NAME:
+#h 	its-terminal - It's The Simple Terminal Selector
+#h
+#h SYNOPSIS:
+#h 	its-terminal [-h|--help]
+#h
+#h DESCRIPTION:
+#h 	 **its-terminal** selects and exectutes your "preferred" terminal emulator
+#h
+#h EXAMPLES:
+#h 	its-terminal
+#h 		Select and execute the preferred terminal emulator
+#h
+#h OVERVIEW:
+#h 	 Look through a list of the most popular terminal emulators
+#h 	 and select our highest priority from those available on the system.
+#h
+#h 	 The selected terminal will be exec'ed.
+#h
+#h OPTIONS:
+#h 	-h, --help
+#h 		Display help text and exit
+#h
+#h EXIT STATUS:
+#h 	0
+#h 		the return code of the terminal
+#h
+#h 	1
+#h 		no preferred terminal found
+#h
+#h ENVIRONMENT:
+#h 	TERMINAL
+#h 		If set, this terminal emulator will have the highest priority.
+#h
+#h HISTORY:
+#h 	2022
+#h 		Created
+#h
+#h BUGS:
+#h 	 https://github.com/stvstnfrd/dotfiles/issues
+#h
+#h VERSIONS:
+#h 	1.0.0
+#h 		initial release
+#h
+set -aeu
+
+help() { grep '^#h' "${1}" | sed 's/^#h \?//g'; }
+
+for option in "${@}"; do case "${option}" in
+    #d Print help text and exit
+    -h|--help) help "${0}"; exit;;
+    *) ;;
+esac; done
 
 command_exists() {
 	command -v "${1}" >/dev/null 2>&1
